### ISSUE TITLE
cannot save my TW classic

### ISSUE THREAD

**Issue by snAkeMB** [twcloud/dropbox#4]
Hi,

thanks for this dropbox app ! works fine for TW5 (on https://twcloud.github.io/tw5-dropbox/#), but it does not offer the possibility to save my old TW Classic. 
I'm usinge : 
https://twcloud.github.io/dropbox/?type=apps#
And I don't have the 'new tiddler' or 'save...' links

thanks for help

**Comment by Arlen22** [comment]
This project has had its ups and downs. The latest TiddlyWiki classic saving problem I'm not quite sure what to do about. At some point soon I will probably implement an iFrame based saver that should cover everything.

**Comment by snAkeMB** [comment]
allright thanks for your answer
